
window.SWL_LOGIN=function($){var submitUrl='/cgi-bin/userLogin';var submitCertUrl='/cert-bin/certVerifyLogin';var mainValidator,otpValidator,rsaValidator;var time_cost=0,timeout_epcinstall=300000;var timeout_plugininstall=30000;var secureServiceURL="https://test.eng.sonicwall.com:19527/postcross";var epc_details="";var epc_redirect="";var epc_oesisversion="";var epc_ignorelegacyopswat=false;var epc_step="";var opswat_version='';var epc_version='';var proxyUser='';var proxyPass='';var proxyAuthTry=0;var proxyNextFunction='';var MAX_PROXY_AUTH_TRY=3;var queryCount=0;function resetMainForm(preserveErrorBanner){$('#password').val('');$('#userPassFormContainer .processing').hide();$('#userPassFormContainer .buttons').show();$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');if(!preserveErrorBanner){SWL_LOGIN.hideError();}}
function setMainFormFocus(){var f=$('#username:blank, #password:blank').get(0);f.blur();f.focus();}
function hideRsa(){SWL_LOGIN.hideError();$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#userPassFormContainer').fadeIn('fast');$('#rsaContainer').fadeOut('fast');setMainFormFocus();}
function hideRadiusChallenge(){SWL_LOGIN.hideError();$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#userPassFormContainer').fadeIn('fast');$('#radiusChallengeContainer').fadeOut('fast');setMainFormFocus();}
function hideChangePw(){SWL_LOGIN.hideError();$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#userPassFormContainer').fadeIn('fast');$('#changePwContainer').fadeOut('fast');setMainFormFocus();}
function cancelEpc(){$('input[name=epcresult]').val('false');$('#epcValidateForm').submit();}
function sendRequest(url,datatype,method,post_data,onsuccess,onerror,timeout){if(url.length==0||datatype.length==0){console.log("url or datetype is empty!");return;}
var agent=navigator.userAgent.toLowerCase();var isIE=false;if(agent.indexOf("msie")!=-1||(agent.indexOf("trident")!=-1))
isIE=true;var str_data=(typeof post_data!='string')?JSONstringify(post_data):post_data;var cross_domain=(url===secureServiceURL)?true:false;console.log("request - str_data:"+str_data);console.log("request - url:"+url);console.log("request - datatype:"+datatype);console.log("request - method:"+method);console.log("request - timeout:"+timeout);console.log("request - cross_domain:"+cross_domain);console.log("request - IE?:"+$.browser.msie);if($.browser.msie&&cross_domain){console.log("XDomainRequest........");var xdr=new XDomainRequest();xdr.onerror=function(){console.log("XDomainRequest failed!!!!!!!!!!!");if(onerror&&typeof onerror=="function"){onerror();}};xdr.onload=function(){var data=$.parseJSON(xdr.responseText);if(onsuccess&&typeof onsuccess=="function"){onsuccess(data);}};if(timeout>0)
xdr.timeout=timeout;xdr.open(method,url);xdr.send(str_data);}else{$.ajax({type:method,url:url,data:str_data,datatype:datatype,crossDomain:cross_domain,success:function(ldata,textStatus,jqXHR){if(onsuccess&&typeof onsuccess=="function"){onsuccess(ldata);}},error:function(ldata,textStatus,errorThrown){if(onerror&&typeof onerror=="function"){onerror(ldata);}}});}}
function updateEpcForm(){console.log("updateEpcForm -epc_step:"+epc_step);if(epc_step=="OESIS_LEGACY"){$('#epc_confirm_msg').text('legacy OESIS found');$('#epcvalidating').hide();$('#epccheckfailed').hide();$('#epc_confirm_no').show();$('#epcmessagebox').show();console.log("1");}else if(epc_step=="OESIS_NOT_INSTALLED"){$('#epc_confirm_msg').text('OESIS not installed');$('#epcvalidating').hide();$('#epccheckfailed').hide();$('#epc_confirm_no').hide();$('#epcmessagebox').show();}else{$('#epcmessagebox').hide();$('#epcprocess').text('Validate EPC ...');$('#epcvalidating').show();$('#epcValidateContainer .processing').show();$('#epccheckfailed').hide();}}
function onEpcCheckFailed(data){$('#epcvalidating').hide();$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#userPassFormContainer').fadeIn('fast');$('#userPassFormContainer .processing').hide();$('#userPassFormContainer .buttons').show();$('#epcValidateContainer').fadeOut('fast');var epcdetail=epc_details;if(epcdetail.length>0)
{epcdetail=epcdetail.replace(/;/g,"<br>");epcdetail=epcdetail.replace(/\\/g,"\\\\");epcdetail=epcdetail.replace(/'/g,"\\\'");$('#invalid_text').html("Login failed - Unable to login due to EPC<br>"
+"<div style='float:right; text-decoration:underline;' onmouseover=\"tt(this, '"+epcdetail+"', 500)\">View Details</div>");$('#invalid').css('display','block');$('#invalid').removeClass('successIcon');}
else
SWL_LOGIN.showError("EPC check failed");}
function onEpcCheckSucceeded(data){console.log("onEpcCheckSucceeded: redirect:"+epc_redirect);if(epc_redirect.length>0)
window.location.href=epc_redirect;}
function onEpcCheckError(data){$('#epcvalidating').hide();$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#userPassFormContainer').fadeIn('fast');$('#userPassFormContainer .processing').hide();$('#userPassFormContainer .buttons').show();$('#epcValidateContainer').fadeOut('fast');if(data=="NORESPONSE")
SWL_LOGIN.showError("Secure Mobile Access Connect Agent no response!");else
SWL_LOGIN.showError("Epc check encounter error");}
function onGetDeviceError(data){$('#password').val('');$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#userPassFormContainer').fadeIn('fast');$('#userPassFormContainer .processing').hide();$('#userPassFormContainer .buttons').show();$('#otpContainer').fadeOut('fast');$('#pdaContainer').fadeOut('fast');if(data=="NORESPONSE")
SWL_LOGIN.showError("Secure Mobile Access Connect Agent no response!");else if(data=="FAILREGISTER")
SWL_LOGIN.showError("Failed to register your device id.");}
function launchGetDeviceIDBySchemeURL(){$.ajax({type:'POST',url:'/cgi-bin/extendauthentication',data:'action=generate',dataType:'html',success:function(data,textStatus,jqXHR){var response=$.parseJSON(data)
if(response){var urlJsonData={action:110,helperversion:SWL_LOGIN.sonicwallSMAConnectAgentVersion,host:window.location.hostname,port:window.location.port?window.location.port:'443',extendid:response.extend_id};setTimeout(queryPDAStatus,1000);SWL_SchemeURL.launchNativeAppBySchemeURL(urlJsonData);}},error:function(data,textStatus,errorThrown){}});}
function queryPDAStatus(){var queryPDAStatusUrl="/cgi-bin/registerDevice?pdaAction=query&ajax=1&rand="+Math.random();$('#pdaContainer').load(queryPDAStatusUrl,function(ldata){if(ldata.indexOf("epccheck")!=-1)
{queryCount=0;$('#pdaContainer').hide();var args=$.parseJSON(ldata);args.status="epccheckfrompda";SWL_SchemeURL.showConnectAgentAlert(launchNativeCallbackHandler,args);}
else if(ldata.indexOf("redirect")!=-1)
{queryCount=0;$('#pdaContainer').hide();var response=$.parseJSON(ldata)
window.location.href=response.redirect;}
else if(ldata.indexOf("registerDeviceForm")!=-1)
{queryCount=0;$('#pdaContainer').html(ldata);$('input').attr('autocomplete','off');$('#pdaContainer').fadeIn('fast');$('#userPassFormContainer:visible').fadeOut('fast');$('#otpContainer').fadeOut('fast');if(($('#pdaStatus').val()==='pending')||($('#pdaStatus').val()==='rejected')||($('#pdaStatus').val()==='full'))
{$('.pdaStatement').css('display','none');$('#pdabuttons').hide();}
else if(($('#pdaStatus').val()==='new'))
{$('#invalid').css('display','none');$('#backToLogin').hide();$('#AcceptRegisterDevice').click(function(){var url="/cgi-bin/registerDevice";var method="POST";var timeout=0;var datatype="text";var post_data="ajax=1&pdaResult=accept";var onsuccess=function(data){if(data.status==='epccheck')
{$('#pdaContainer').hide();data.status="epccheckfrompda";SWL_SchemeURL.showConnectAgentAlert(launchNativeCallbackHandler,data);}
else if(data.status==='success')
{$('#pdaContainer').hide();window.location.href=data.redirect;}
else if(data.indexOf("pdaLogoutMsg")!=-1)
{$('#pdaContainer').html(data);$('.pdaStatement').css('display','none');$('#pdabuttons').hide();}
else
{onGetDeviceError();}};var onerror=function(){onGetDeviceError("FAILREGISTER");};sendRequest(url,datatype,method,post_data,onsuccess,onerror,timeout);});$('#RefuseRegisterDevice').click(function(){var url="/cgi-bin/registerDevice";var method="POST";var timeout=0;var datatype="text";var post_data="ajax=1&pdaResult=decline";var onsuccess=function(data){$('#invalid').css('display','block');$('#pdaContainer').fadeOut('fast');$('#userPassFormContainer').fadeIn('fast');resetMainForm();};var onerror=function(){onGetDeviceError("FAILREGISTER");};sendRequest(url,datatype,method,post_data,onsuccess,onerror,timeout);});}}
else
{if(queryCount<180)
{queryCount+=1;setTimeout(queryPDAStatus,1000);}
else
{queryCount=0;onGetDeviceError("NORESPONSE");}}});}
function showRadiusChallenge(jsonData){$('#radiusChallengeContainer').load('/cgi-bin/radiusChallengeLogin',jsonData,function(){$('input').attr('autocomplete','off');$('#userPassFormContainer:visible').fadeOut('fast',function(){resetMainForm();});$(this).fadeIn('fast',function(){$('#radiusChallengeContainer input:first').get(0).focus();$('#cancelRadius').click(function(){SWL_LOGIN.hideError();$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#userPassFormContainer').fadeIn('fast');$('#radiusChallengeContainer').fadeOut('fast');setMainFormFocus();});});if(jsonData.status==='needchallenge'){rsaValidator=$('form[name=radiusChallengeForm]').validate({submitHandler:function(form){$(form).ajaxSubmit({dataType:'json',beforeSubmit:function(){$('#radiusChallengeContainer .buttons').hide();$('#radiusChallengeContainer .processing').show();},success:function(data){if(data.status==='success'){window.location.href=data.redirect;return;}else if(data.status==='needchallenge'){showRadiusChallenge(data);}else if(data.status==='needOtp'){SWL_LOGIN.showOtp('/cgi-bin/otp',data);}else if(data.status==='epccheck'){SWL_SchemeURL.showConnectAgentAlert(launchNativeCallbackHandler,data);}else{hideRadiusChallenge();SWL_LOGIN.showError(data.message);}},error:function(XMLHttpRequest,textStatus,errorThrown){$('#radiusChallengeContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#radiusChallengeContainer .processing').hide();$('#radiusChallengeContainer .buttons').show();}});$('#radiusChallengeContainer').find(':text, :password, :submit, select').attr('disabled','disabled');},showErrors:function(errorMap,errorList){}});}});}
function showRsa(jsonData){$('#rsaContainer').load('/cgi-bin/rsaLogin',jsonData,function(){$('input').attr('autocomplete','off');$('#userPassFormContainer:visible').fadeOut('fast',function(){resetMainForm();});$(this).fadeIn('fast',function(){if(jsonData.err){SWL_LOGIN.showError(jsonData.err);}});if(jsonData.status==='newpin'){rsaValidator=$('form[name=newpinForm]').validate({submitHandler:function(form){$(form).ajaxSubmit({dataType:'json',beforeSubmit:function(){$('#rsaContainer .buttons').hide();$('#rsaContainer .processing').show();},success:function(data){if(data.status==='success'){hideRsa();SWL_LOGIN.showError(data.message,true);}else if(data.status==='nomatch'){$('#rsaContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#rsaContainer input[type=password]').val('');$('#rsaContainer input:first').get(0).focus();$('#rsaContainer .processing').hide();$('#rsaContainer .buttons').show();SWL_LOGIN.showError(data.message);}else{hideRsa();SWL_LOGIN.showError(data.message);}},error:function(XMLHttpRequest,textStatus,errorThrown){hideRsa();}});$('#rsaContainer').find(':text, :password, :submit, select').attr('disabled','disabled');},showErrors:function(errorMap,errorList){}});$('#rsaContainer input:first').get(0).focus();$('#cancelRsa').click(hideRsa);}else if(jsonData.status==='syspin'){$('form[name=syspinForm]').ajaxForm({dataType:'json',beforeSubmit:function(){$('#rsaContainer .buttons').hide();$('#rsaContainer .processing').show();},success:function(data){if(data.status==='success'){hideRsa();SWL_LOGIN.showError(data.message,true);}else if(/newpin|syspin/.test(data.status)){showRsa(data);return;}else{hideRsa();SWL_LOGIN.showError(data.message);}},error:function(XMLHttpRequest,textStatus,errorThrown){hideRsa();}});$('#sysPinYes').click(function(){$('#sysreply').val('y');$('form[name=syspinForm]').submit();});$('#sysPinNo').click(function(){$('#sysreply').val('n');$('form[name=syspinForm]').submit();});}else if(jsonData.status==='nextcode'){rsaValidator=$('form[name=nextcodeForm]').validate({submitHandler:function(form){$(form).ajaxSubmit({dataType:'json',beforeSubmit:function(){$('#rsaContainer .buttons').hide();$('#rsaContainer .processing').show();},success:function(data){if(data.status==='success'){window.location.href=data.redirect;}else{hideRsa();SWL_LOGIN.showError(data.message);}},error:function(XMLHttpRequest,textStatus,errorThrown){hideRsa();}});},showErrors:function(errorMap,errorList){}});$('#rsaContainer input:first').get(0).focus();$('#cancelRsa').click(hideRsa);}});}
$(document).ready(function(){$('input').attr('autocomplete','off');$('#username').get(0).focus();$.cookie('SessURL',SWL_LOGIN.parseLoginHref(window.location.href),{expires:7,path:'/',secure:true});if(document.ajaxBasedLogin!==false){$('input[name=web]').remove();$('form[name=Login]').append('<input type="hidden" name="ajax" value="true">').ajaxForm({dataType:'json',url:submitUrl,beforeSubmit:function(formDataArray,formJQuery,ajaxOpts){var form=document.Login;ajaxOpts.url=(form.action.indexOf(submitCertUrl)<0)?submitUrl:submitCertUrl;var isDomainSelect=typeof($("#domain").get(0).options)=='undefined'?0:1;if(form.username.value===""&&(form.action.indexOf(submitCertUrl)<0)&&isDomainSelect){SWL_LOGIN.showError("Please enter a user name");form.username.focus();return false;}
if(form.password.value===""&&(form.action.indexOf(submitCertUrl)<0)&&isDomainSelect){SWL_LOGIN.showError("Please enter a password");form.password.focus();return false;}
$.cookie('svDomainName',$('#domain').val(),{expires:365,path:'/cgi-bin/welcome'});$.cookie('svDomainName',$('#domain').val(),{expires:365,path:'/cgi-bin/welcome/'});$.cookie('nxAutoLaunched',null);$('#userPassFormContainer .buttons').hide();$('#userPassFormContainer .processing').show();SWL_LOGIN.hideError();return true;},success:function(data){var form=document.Login;if(data.status==='success'){window.location.href=data.redirect;}else if(data.status==='needOtp'){SWL_LOGIN.showOtp('/cgi-bin/otp',data);}else if(data.status==='needChangePw'){SWL_LOGIN.showChangePw(data.token);}else if(data.status==='needClientCert'){form.verifyCert.value=1;$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');if(!$.browser.mozilla){form.action='/cert-bin/certVerifyLogin';form.ajax.disabled=true;form.submit();$('#userPassFormContainer').find(':text, :password, :submit, select').attr('disabled','disabled');}else{form.action='/cert-bin/certVerifyLogin';form.ajax.disabled=true;form.submit();$('#userPassFormContainer').find(':text, :password, :submit, select').attr('disabled','disabled');}
return;}else if(/newpin|syspin|nextcode/.test(data.status)){showRsa(data);}else if(data.status==='needchallenge'){showRadiusChallenge(data);}else if(data.status==='pdarequired'){SWL_SchemeURL.showConnectAgentAlert(launchNativeCallbackHandler,data);}else if(data.status==='epccheck'){SWL_SchemeURL.showConnectAgentAlert(launchNativeCallbackHandler,data);}else{SWL_LOGIN.showError(data.message);$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#password').val('');$('#userPassFormContainer .processing').hide();$('#userPassFormContainer .buttons').show();setMainFormFocus();showLoginBoxFields(document.Login.domain.selectedIndex);}},error:function(XMLHttpRequest,textStatus,errorThrown){$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#password').val('');$('#userPassFormContainer .processing').hide();$('#userPassFormContainer .buttons').show();setMainFormFocus();showLoginBoxFields(document.Login.domain.selectedIndex);}}).bind('form-submit-notify',function(){$('#userPassFormContainer').find(':text, :password, :submit, select').attr('disabled','disabled');});}});function epcProxyAuth(nextFunc){if(proxyNextFunction.value!=nextFunc.value)
proxyAuthTry=1;else
proxyAuthTry++;proxyNextFunction=nextFunc;$('#epcvalidating').hide();$('#epccheckfailed').hide();$('#epcproxyAuthPage').show();return;}
if(typeof console==="undefined"){console={log:function(){}};}
function querySessionStatus(){console.log('query session status');$.ajax({url:'/cgi-bin/sessionStatus',dataType:'json',success:function(data,textStatus,jqXHR){if(!data||data.status=='notfound'){queryCount=0;console.log("session query: notfound");onEpcCheckFailed();return;}
var epcStatus=data.epcStatus;if(epcStatus===1||epcStatus===3)
{queryCount=0;onEpcCheckSucceeded();}
else
{if(queryCount<180){queryCount+=1;setTimeout(querySessionStatus,1000);}
else{queryCount=0;onEpcCheckError('NORESPONSE');}}},error:function(data,textStatus,errorThrown){queryCount=0;onEpcCheckFailed();}});}
function launchEPCCheckBySchemeURL(){console.log('f:launchEPCCheckBySchemeURL');$.ajax({type:'POST',url:'/cgi-bin/extendauthentication',data:'action=generate',dataType:'html',success:function(data,textStatus,jqXHR){var response=$.parseJSON(data)
if(response){var urlJsonData={action:50,helperversion:SWL_LOGIN.sonicwallSMAConnectAgentVersion,host:window.location.hostname,port:window.location.port?window.location.port:'443',extendid:response.extend_id};setTimeout(querySessionStatus,1000);SWL_SchemeURL.launchNativeAppBySchemeURL(urlJsonData);}},error:function(data,textStatus,errorThrown){}});}
function launchNativeCallbackHandler(args){if(args.status==='epccheck'){SWL_LOGIN.showEpcValidateJson(args);}
else if(args.status==='epccheckfrompda'){SWL_LOGIN.showEcpValidateFromPdaJson(args);}
else if(args.status==='pdarequired'){SWL_LOGIN.showPDARequired(args);}}
return{parseLoginHref:function(href){var ques=href.indexOf('?');if(ques>=0)
return href.substring(0,ques);else
return href;},onEpcProxyAuthNextBtn:function(){var validatePage=document.getElementById("epcvalidating");var proxyAuthPage=document.getElementById("epcproxyAuthPage");var failedPage=document.getElementById("epccheckfailed");if(proxyAuthPage){proxyUser=document.getElementById("proxy_user").value;proxyPass=document.getElementById("proxy_pass").value;$('#proxy_user').val('');$('#proxy_pass').val('');if(proxyUser=='')
{alert("Invalid user name!");document.getElementById('proxy_user').focus();return;}
if(proxyPass=='')
{alert("Invalid password!");document.getElementById('proxy_pass').focus();return;}}
$('#epccheckfailed').hide();$('#epcproxyAuthPage').hide();$('#epcvalidating').show();setTimeout(proxyNextFunction,50);return;},installEpc:function(){EPCLaunchX1.SetIEProxy();EPCLaunchX1.SetProxyAuth(proxyUser,proxyPass);EPCLaunchX1.DownloadNACAgent();if(0>EPCLaunchX1.statusId){alert("Download Epc Agent failed.");return;}
$('#epcprocess').text('Installing EPC Agent...');time_cost=500;setTimeout(function(){SWL_LOGIN.epcInstallWait();},500);return;},onEpcInstalled:function(){SWL_LOGIN.installOesis();},onOesisInstalled:function(){time_cost=0;$('#epcprocess').text('Checking EPC ...');EPCLaunchX1.SetIEProxy();EPCLaunchX1.SetProxyAuth(proxyUser,proxyPass);EPCLaunchX1.EPCCheck(1,0);if(0!=EPCLaunchX1.statusId){var epcfailedmessage="Epc check failed";if(2==EPCLaunchX1.statusId)
{if(MAX_PROXY_AUTH_TRY<proxyAuthTry)
{epcfailedmessage="Incorrect user/password, proxy authentication failed!";proxyAuthTry=0;}
else
{time_cost=0;epcProxyAuth(SWL_LOGIN.onOesisInstalled);return;}}
else if(-4==EPCLaunchX1.statusId)
{}
else if(-5==EPCLaunchX1.statusId)
{epcfailedmessage="Failed to start EPC Agent";}
else
{epcfailedmessage="EPC check failed";}
$('#epcvalidating').hide();$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#userPassFormContainer').fadeIn('fast');$('#userPassFormContainer .processing').hide();$('#userPassFormContainer .buttons').show();$('#epcValidateContainer').fadeOut('fast');var epcdetail=EPCLaunchX1.strFailedProfilesDetail;if(epcdetail!=null&&epcdetail.length>0)
{epcdetail=epcdetail.replace(/;/g,"<br>");epcdetail=epcdetail.replace(/\\/g,"\\\\");$('#invalid_text').html("Login failed - Unable to login due to EPC<br>"
+"<div style='float:right; text-decoration:underline;' onmouseover=\"tt(this, '"+epcdetail+"', 500)\">View Details</div>");$('#invalid').css('display','block');$('#invalid').removeClass('successIcon');}
else
SWL_LOGIN.showError(epcfailedmessage);}
else{$('input[name=epcresult]').val('true');$('#epcValidateForm').submit();}},epcInstallWait:function()
{if(time_cost>timeout_epcinstall){SWL_LOGIN.showError("Epc install failed");time_cost=0;return;}
EPCLaunchX1.CheckNACAgentInstalled(epc_version);if(0!=EPCLaunchX1.statusId){var dlStatus=EPCLaunchX1.downloadStatus;if(dlStatus==2)
{time_cost=0;epcProxyAuth(SWL_LOGIN.installEpc);return;}
else if(dlStatus==-1)
{SWL_LOGIN.showError("Download EPC Agent failed");time_cost=0;return;}
time_cost+=200;setTimeout('SWL_LOGIN.epcInstallWait()',200);return;}
SWL_LOGIN.installOesis();},installOesis:function(){if(time_cost>timeout_epcinstall){SWL_LOGIN.showError("Epc install failed");time_cost=0;return;}
try{if(opswat_version.length>0){EPCLaunchX1.SetIEProxy();EPCLaunchX1.SetProxyAuth(proxyUser,proxyPass);EPCLaunchX1.VerifyOesisAsyc(opswat_version);if(0>EPCLaunchX1.statusId){}
time_cost=500;setTimeout('SWL_LOGIN.oesisInstallWait()',500);}
else
SWL_LOGIN.onOesisInstalled();}catch(err){console.log("legacy plugin found, go on with EPC check");SWL_LOGIN.onOesisInstalled();}},oesisInstallWait:function(){var dlStatus=EPCLaunchX1.downloadStatus;if(1!=dlStatus){if(dlStatus==2)
{time_cost=0;epcProxyAuth(SWL_LOGIN.installOesis);return;}
SWL_LOGIN.onOesisInstalled();}
else
{time_cost+=200;setTimeout('SWL_LOGIN.oesisInstallWait()',200);}},showError:function(err,success){$('#invalid_text').text(err);$('#invalid').css('display','block');if(success){$('#invalid').addClass('successIcon');}else{$('#invalid').removeClass('successIcon');}},hideError:function(){$('#invalid').css('display','none');},epcPluginInstallWait:function(){if(time_cost>timeout_plugininstall){time_cost=0;return;}
if((typeof(EPCLaunchX1)=='undefined')||(EPCLaunchX1.object==null)){time_cost+=200;setTimeout('SWL_LOGIN.epcPluginInstallWait()',200);return;}
else
{location.reload();}},onEpcConfirm:function(type){console.log("onEpcConfirm - epc_step:"+epc_step);if(epc_step=="OESIS_LEGACY"){if(type=="YES"){epc_ignorelegacyopswat=true;var post_data={"epcOesisVersion":epc_oesisversion,"redirect":epc_redirect};$('#epcmessagebox').hide();$('#epcprocess').text('Validate EPC ...');$('#epcvalidating').show();$('#epcValidateContainer .processing').show();$('#epccheckfailed').hide();epcGetProfiles();}
else{cancelEpc();}}else if(epc_step=="OESIS_NOT_INSTALLED"){cancelEpc();}
epc_step="";},showEpcValidateJson:function(jsonData){$('#epcValidateContainer').load('/cgi-bin/epcValidate',jsonData,function(){$('input').attr('autocomplete','off');epc_step="";$('#userPassFormContainer').fadeOut('fast');$('#radiusChallengeContainer').fadeOut('fast');$('#otpContainer').fadeOut('fast');$(this).fadeIn('fast',function(){updateEpcForm();});$('#cancelEpc').click(cancelEpc);console.log("showEpcValidateNew - json:"+JSONstringify(jsonData));if(jsonData.epcOesisVersion)
epc_oesisversion=jsonData.epcOesisVersion;else
console.log("jsonData.epcOesisVersion undefined");epc_redirect=jsonData.redirect;launchEPCCheckBySchemeURL();});},showEcpValidateFromPdaJson:function(jsonData){jsonData.status="epccheck";$('#epcValidateContainer').load('/cgi-bin/epcValidate',jsonData,function(){$('input').attr('autocomplete','off');epc_step="";$('#userPassFormContainer').fadeOut('fast');$('#radiusChallengeContainer').fadeOut('fast');$('#otpContainer').fadeOut('fast');$(this).fadeIn('fast',function(){updateEpcForm();});$('#cancelEpc').click(cancelEpc);console.log("showEpcValidateNew - json:"+JSONstringify(jsonData));if(jsonData.epcOesisVersion)
epc_oesisversion=jsonData.epcOesisVersion;else
console.log("jsonData.epcOesisVersion undefined");epc_redirect=jsonData.redirect;setTimeout(querySessionStatus,1000);});},showPDARequired:function(jsonData){launchGetDeviceIDBySchemeURL();},showOtp:function(reqPath,jsonData){$('#otpContainer').load(reqPath,function(){$('input').attr('autocomplete','off');$('#radiusChallengeContainer').fadeOut('fast',function(){resetMainForm();});$('#userPassFormContainer').fadeOut('fast',function(){resetMainForm();});$(this).fadeIn('fast',function(){if($('#otpcode').length){$('#otpcode').get(0).focus();}
$('#cancelOtp').click(function(){SWL_LOGIN.hideError();$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#userPassFormContainer').fadeIn('fast');$('#otpContainer').fadeOut('fast');setMainFormFocus();});if($('#appBindLink').length){$('#appBindLink').click(function(){$.ajax({type:'POST',url:'/cgi-bin/totp',data:'action=bind&from=login&hostname='+window.location.hostname,dataType:'html',success:function(data,textStatus,jqXHR){var response=$.parseJSON(data);if(response){if(response.status&&response.status==='failure'){console.error(response.reason);}
else{var otpauthURL="otpauth://totp/";otpauthURL+=response.label;otpauthURL+="?secret="+response.key;otpauthURL+="&algorithm="+response.algo;otpauthURL+="&digits="+response.digits;otpauthURL+="&period="+response.period;$('#appQRCode').html('');$('#appQRCode').attr('title','');$('#appQRCode').qrcode({minVersion:6,ecLevel:'H',quiet:1,width:166,height:166,text:otpauthURL,mode:4,radius:0.35,mSize:0.2,image:$('#img-buffer')[0]});$('#appQRCode').show();$('#appQRCode').attr('title',response.key);$('#appKeyCode').html(response.key);$('#appBindInstruments').show();}}},error:function(data,textStatus,errorThrown){}});});}
if($('#showAppKeyCode').length){$('#showAppKeyCode').click(function(){$('#appKeyCodeContent').show();});}
if($('#useBackupCodeLink').length){$('#useBackupCodeLink').click(function(){SWL_LOGIN.showOtp('/cgi-bin/otp?action=3');});}
if($('#useEmailLink').length){$('#useEmailLink').click(function(){SWL_LOGIN.showOtp('/cgi-bin/otp?action=1');});}
if($('#useAppLink').length){$('#useAppLink').click(function(){SWL_LOGIN.showOtp('/cgi-bin/otp?action=2');});}});otpValidator=$('form[name=otpForm]').validate({submitHandler:function(form){$(form).ajaxSubmit({dataType:'json',beforeSubmit:function(){$('#otpContainer .buttons').hide();$('#otpContainer .processing').show();},success:function(data){if(data.status==='success'){window.location.href=data.redirect;return;}else if(data.status==='noPass'){SWL_LOGIN.showError("Please enter your password and try again.");}else if(data.status==='pdarequired'){SWL_SchemeURL.showConnectAgentAlert(launchNativeCallbackHandler,data);return;}else if(data.status==='epccheck'){SWL_SchemeURL.showConnectAgentAlert(launchNativeCallbackHandler,data);return;}else{SWL_LOGIN.showError(data.message);if(data.status==='lockout'){$('#userPassFormContainer').find(':text, :password, :submit, select, a').removeAttr('disabled');$('#userPassFormContainer').fadeIn('fast');$('#otpContainer').fadeOut('fast');setMainFormFocus();}}
$('#otpContainer').find(':text, :password, :submit, select, a').removeAttr('disabled');if($('#otpcode').length){$('#otpcode').val('').get(0).focus();}
$('#otpContainer .processing').hide();$('#otpContainer .buttons').show();},error:function(XMLHttpRequest,textStatus,errorThrown){$('#otpContainer').find(':text, :password, :submit, select, a').removeAttr('disabled');$('#otpContainer .processing').hide();$('#otpContainer .buttons').show();}});$('#otpContainer').find(':text, :password, :submit, select, a').attr('disabled','disabled');},rules:{password:{required:':password:filled'}}});});},showChangePw:function(token){SWL_LOGIN.showError("You must change your password before logging in.");$.cookie("token",token,{path:'/cgi-bin/loginChangePass',secure:true});$('#changePwContainer').load('/cgi-bin/loginChangePass',function(){$.cookie("token",null,{path:'/cgi-bin/loginChangePass',secure:true});$('input').attr('autocomplete','off');$('#userPassFormContainer').fadeOut('fast',function(){$('#changePwContainer').find('input[name=username]').val($('#username').val()).end().find('input[name=domain]').val($('#domain').val());resetMainForm(true);});$(this).fadeIn('fast',function(){$('#oldPass').get(0).focus();$('#cancelChangePw').click(function(){SWL_LOGIN.hideError();$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#userPassFormContainer').fadeIn('fast');$('#changePwContainer').fadeOut('fast');setMainFormFocus();});});changePwValidator=$('form[name=changePwForm]').validate({submitHandler:function(form){$(form).ajaxSubmit({dataType:'json',beforeSubmit:function(){$('#changePwContainer .buttons').hide();$('#changePwContainer .processing').show();},success:function(data){if(data.status==='success'){hideChangePw();SWL_LOGIN.showError("Your password has been changed.  Please log in again.",true);return;}else if(data.status==='incomplete'){SWL_LOGIN.showError("Please fill in all fields and try again.");}else{SWL_LOGIN.showError(data.message);if(data.status==='lockout'){$('#userPassFormContainer').find(':text, :password, :submit, select').removeAttr('disabled');$('#userPassFormContainer').fadeIn('fast');$('#changePwContainer').fadeOut('fast');setMainFormFocus();}}
$('form[name=changePwForm]').get(0).reset();$('#changePwContainer').find('input[name=username]').val($('#username').val()).end().find('input[name=domain]').val($('#domain').val());$('#changePwContainer').find(':text, :password, :submit, select').removeAttr('disabled').end().find('.processing').hide().end().find('.buttons').show();},error:function(XMLHttpRequest,textStatus,errorThrown){$('#changePwContainer').find(':text, :password, :submit, select').removeAttr('disabled').end().find('.processing').hide().end().find('.buttons').show();}});$('#changePwContainer').find(':text, :password, :submit, select').attr('disabled','disabled');},showErrors:function(errorMap,errorList){if(this.numberOfInvalids()>0){SWL_LOGIN.showError("Please fill in all fields and try again.");}else{SWL_LOGIN.hideError();}}});});},excuteTwoFactorAuthenticate:function(data){if(/newpin|syspin|nextcode/.test(data.status)){showRsa(data);}else if(data.status==='needchallenge'){showRadiusChallenge(data);}}};}(jQuery);