
window.SWL_SchemeURL=function($){var agent=navigator.userAgent.toLowerCase();function appendConnectInstallAlertForLoginPage(){var htmlString="<div id=\"connectAgentAlertContainer\" style=\"display:none\">";htmlString+="<table>";htmlString+="<tr>";htmlString+="<td>";htmlString+="<p id=\"connectAgentAlertMessage\">";htmlString+="Please install the SMA Connect Agent for optimal performance when launching bookmarks and clients. <a href=\"/connectagentdetail.html\" target=\"_blank\">[Details]</a>";htmlString+="</p>";htmlString+="</td>";htmlString+="</tr>";htmlString+="<tr>";htmlString+="<td>";htmlString+="<input type=\"button\" class=\"button\" value=\"Download\" id=\"connectAgentDownload\" onclick=\"SWL_SchemeURL.connectAgentDownload()\"> ";htmlString+="<input type=\"button\" class=\"button\" value=\"Installed\" id=\"connectAgentInstalled\"> ";htmlString+="<input type=\"button\" class=\"button\" value=\"Continue\" id=\"connectAgentContinue\"> ";htmlString+="</td>";htmlString+="</tr>";htmlString+="</table>";htmlString+="</div>";$("#login_table").append(htmlString);}
function appendConnectInstallAlertForPortalPage(){var htmlString="<div id=\"connectAgentAlertDialog\" class=\"dialog\" style=\"display:none\">";htmlString+="<div class=\"dialogQuestion\">";htmlString+="Please install the SMA Connect Agent. <a href=\"/connectagentdetail.html\" target=\"_blank\">[Details]</a>";htmlString+="</div>";htmlString+="<div class=\"buttons\">";htmlString+="<input type=\"button\" id=\"connectAgentDownload\" value=\"Download\" onclick=\"SWL_SchemeURL.connectAgentDownload()\"> ";htmlString+="<input type=\"button\" id=\"connectAgentInstalled\" value=\"Installed\"> ";htmlString+="<input type=\"button\" id=\"connectAgentContinue\" value=\"Continue\"> ";htmlString+="</div></div>";$("body").append(htmlString);}
function showConnectAgentAlertForLoginPage(callback,args){var noteServiceDownload=$.cookie('connectAgentInstalled');if(noteServiceDownload!='YES'){if(args.status==='epccheckfrompda'){callback(args);return;}
$('#userPassFormContainer').fadeOut('fast');$('#otpContainer').fadeOut('fast');$('#connectAgentInstalled').unbind('click').bind('click',{args:args},function(event){$('#connectAgentAlertContainer').hide();$.cookie('connectAgentInstalled','YES',{expires:1080,path:'/',secure:true});$.cookie('connectAgentInstalled','YES',{expires:1080,path:'/cgi-bin',secure:true});$.cookie('connectAgentInstalled','YES',{expires:1080,path:'/cgi-bin/',secure:true});callback(event.data.args);});$('#connectAgentContinue').unbind('click').bind('click',{args:args},function(event){$('#connectAgentAlertContainer').hide();callback(event.data.args);});if(args.status==='epccheck'){$('#connectAgentAlertMessage').html("SMA Connect Agent required to continue with EPC. <a href=\"/connectagentdetail.html\" target=\"_blank\">[Details]</a>");}
else if(args.status==='pdarequired'){$('#connectAgentAlertMessage').html("SMA Connect Agent required to continue with PDA. <a href=\"/connectagentdetail.html\" target=\"_blank\">[Details]</a>");}
$('#connectAgentAlertContainer').show();}
else{callback(args);}}
function showConnectAgentAlertForPortalPage(callback,args){var noteServiceDownload=$.cookie('connectAgentInstalled');if(noteServiceDownload!='YES'){$.blockUI({message:$("#connectAgentAlertDialog"),css:{cursor:'default',padding:'20px',width:'360px',border:'3px solid #111'},overlayCSS:{opacity:0.3}});$('#connectAgentInstalled').unbind('click').bind('click',{args:args},function(event){$.cookie('connectAgentInstalled','YES',{expires:1080,path:'/',secure:true});$.cookie('connectAgentInstalled','YES',{expires:1080,path:'/cgi-bin',secure:true});$.cookie('connectAgentInstalled','YES',{expires:1080,path:'/cgi-bin/',secure:true});$.unblockUI();callback(event.data.args);});$('#connectAgentContinue').unbind('click').bind('click',{args:args},function(event){$.unblockUI();callback(event.data.args);});}
else{$.unblockUI();callback(args);}}
$(document).ready(function(){if(typeof SWL_LOGIN!=="undefined"){appendConnectInstallAlertForLoginPage();}
else if(typeof SWL_PORTALV2!=="undefined"){appendConnectInstallAlertForPortalPage();}
else{appendConnectInstallAlertForPortalPage();}});return{connectAgentDownload:function(){window.open("/cgi-bin/clientdownloads","Client Downloads","width=750,height=650,toolbar=no,menubar=no,location=no,resizable");},showConnectAgentAlert:function(callback,args){if(typeof SWL_LOGIN!=='undefined'){showConnectAgentAlertForLoginPage(callback,args);}
else{showConnectAgentAlertForPortalPage(callback,args);}},launchNativeAppBySchemeURL:function(urlJsonData,callback,args){var JSON_stringify=window.JSONstringify||JSON.stringify;var urlJsonString=JSON_stringify(urlJsonData);var data=[];for(var i=0;i<urlJsonString.length;i++){data.push(urlJsonString.charCodeAt(i));}
var launchURL="sonicwallconnectagent://"+Base64.encode(data).replace(/=/g,"%3D");if(/windows/.test(agent)){if(launchURL.length>2046){alert("The Scheme URL is too long to launch Connect Agent.");return;}}
window.location.href=launchURL;if(callback){callback(args);}}};}(jQuery);